In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import requests, re, time
from bs4 import BeautifulSoup
import scraping_class
import pprint
import pandas as pd
import numpy as np
logfile = 'log.csv'## name your log file.
connector = scraping_class.Connector(logfile)
session = requests.session()
session.headers['mkp244@alumni.ku.dk'] = 'mkp244@alumni.ku.dk' 
session.headers['Oluf Kelkjær'] = 'Oluf Kelkjær'
session.headers

{'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'mkp244@alumni.ku.dk': 'mkp244@alumni.ku.dk', 'Oluf Kelkjær': 'Oluf Kelkjær'}

# Importing the packages

# Importing and parsing the data

In [5]:
url='https://www.imdb.com/chart/top'
number_of_movies = 250
response = requests.get(url)

if response.ok:
    html = response.text
else:
    print('error')
    
soup = BeautifulSoup(html,'html.parser')

link_location = html.split('href="')[1:]

links = set()


for link_loc in link_location:
    link = link_loc.split('"')[0]
    if '/title/' in link:
        links.add(link)
        
links = ['https://www.imdb.com/'+ link for link in links if not 'ref' in link]# add the domain to each link
links

links_r = [x+'ratings' for x in links]
links_r

['https://www.imdb.com//title/tt0095765/ratings',
 'https://www.imdb.com//title/tt3011894/ratings',
 'https://www.imdb.com//title/tt1895587/ratings',
 'https://www.imdb.com//title/tt0118799/ratings',
 'https://www.imdb.com//title/tt0361748/ratings',
 'https://www.imdb.com//title/tt2758880/ratings',
 'https://www.imdb.com//title/tt0372784/ratings',
 'https://www.imdb.com//title/tt0072684/ratings',
 'https://www.imdb.com//title/tt0055630/ratings',
 'https://www.imdb.com//title/tt0070735/ratings',
 'https://www.imdb.com//title/tt1454029/ratings',
 'https://www.imdb.com//title/tt0040897/ratings',
 'https://www.imdb.com//title/tt0015324/ratings',
 'https://www.imdb.com//title/tt1954470/ratings',
 'https://www.imdb.com//title/tt0031679/ratings',
 'https://www.imdb.com//title/tt0056732/ratings',
 'https://www.imdb.com//title/tt0056592/ratings',
 'https://www.imdb.com//title/tt0074958/ratings',
 'https://www.imdb.com//title/tt1255953/ratings',
 'https://www.imdb.com//title/tt5311514/ratings',
 'https://www.imdb.com//title/tt0079944/ratings',
 'https://www.imdb.com//title/tt0022100/ratings',
 'https://www.imdb.com//title/tt0116231/ratings',
 'https://www.imdb.com//title/tt0076759/ratings',
 'https://www.imdb.com//title/tt2380307/ratings',
 'https://www.imdb.com//title/tt0042876/ratings',
 'https://www.imdb.com//title/tt0120586/ratings',
 'https://www.imdb.com//title/tt0105695/ratings',
 'https://www.imdb.com//title/tt0040522/ratings',
 'https://www.imdb.com//title/tt0059578/ratings',
 'https://www.imdb.com//title/tt1205489/ratings',
 'https://www.imdb.com//title/tt0112471/ratings',
 'https://www.imdb.com//title/tt0050986/ratings',
 'https://www.imdb.com//title/tt4154796/ratings',
 'https://www.imdb.com//title/tt0120382/ratings',
 'https://www.imdb.com//title/tt2582802/ratings',
 'https://www.imdb.com//title/tt0068646/ratings',
 'https://www.imdb.com//title/tt0047296/ratings',
 'https://www.imdb.com//title/tt0264464/ratings',
 'https://www.imdb.com//title/tt0167261/ratings',
 'https://www.imdb.com//title/tt0407887/ratings',
 'https://www.imdb.com//title/tt1832382/ratings',
 'https://www.imdb.com//title/tt0758758/ratings',
 'https://www.imdb.com//title/tt0374887/ratings',
 'https://www.imdb.com//title/tt0109830/ratings',
 'https://www.imdb.com//title/tt0112573/ratings',
 'https://www.imdb.com//title/tt0091763/ratings',
 'https://www.imdb.com//title/tt2024544/ratings',
 'https://www.imdb.com//title/tt0017925/ratings',
 'https://www.imdb.com//title/tt0081505/ratings',
 'https://www.imdb.com//title/tt5027774/ratings',
 'https://www.imdb.com//title/tt0198781/ratings',
 'https://www.imdb.com//title/tt0114369/ratings',
 'https://www.imdb.com//title/tt0036775/ratings',
 'https://www.imdb.com//title/tt0050976/ratings',
 'https://www.imdb.com//title/tt5074352/ratings',
 'https://www.imdb.com//title/tt0071562/ratings',
 'https://www.imdb.com//title/tt0073707/ratings',
 'https://www.imdb.com//title/tt0025316/ratings',
 'https://www.imdb.com//title/tt1392214/ratings',
 'https://www.imdb.com//title/tt0169102/ratings',
 'https://www.imdb.com//title/tt1345836/ratings',
 'https://www.imdb.com//title/tt0209144/ratings',
 'https://www.imdb.com//title/tt0072443/ratings',
 'https://www.imdb.com//title/tt0053125/ratings',
 'https://www.imdb.com//title/tt0892769/ratings',
 'https://www.imdb.com//title/tt0047478/ratings',
 'https://www.imdb.com//title/tt0056172/ratings',
 'https://www.imdb.com//title/tt0477348/ratings',
 'https://www.imdb.com//title/tt0083658/ratings',
 'https://www.imdb.com//title/tt0364569/ratings',
 'https://www.imdb.com//title/tt1305806/ratings',
 'https://www.imdb.com//title/tt0050825/ratings',
 'https://www.imdb.com//title/tt0117951/ratings',
 'https://www.imdb.com//title/tt0363163/ratings',
 'https://www.imdb.com//title/tt0041959/ratings',
 'https://www.imdb.com//title/tt4154756/ratings',
 'https://www.imdb.com//title/tt0027977/ratings',
 'https://www.imdb.com//title/tt0017136/ratings',
 'https://www.imdb.com//title/tt0096283/ratings',
 'https://www.imdb.com//title/tt0113277/ratings',
 'https://www.imdb.com//title/tt0034583/ratings',
 'https://www.imdb.com//title/tt0080678/ratings',
 'https://www.imdb.com//title/tt0118715/ratings',
 'https://www.imdb.com//title/tt0089881/ratings',
 'https://www.imdb.com//title/tt0103064/ratings',
 'https://www.imdb.com//title/tt0133093/ratings',
 'https://www.imdb.com//title/tt0064116/ratings',
 'https://www.imdb.com//title/tt0033467/ratings',
 'https://www.imdb.com//title/tt3315342/ratings',
 'https://www.imdb.com//title/tt0080684/ratings',
 'https://www.imdb.com//title/tt0110912/ratings',
 'https://www.imdb.com//title/tt0110357/ratings',
 'https://www.imdb.com//title/tt0245429/ratings',
 'https://www.imdb.com//title/tt1375666/ratings',
 'https://www.imdb.com//title/tt0137523/ratings',
 'https://www.imdb.com//title/tt0071315/ratings',
 'https://www.imdb.com//title/tt0012349/ratings',
 'https://www.imdb.com//title/tt0031381/ratings',
 'https://www.imdb.com//title/tt0077416/ratings',
 'https://www.imdb.com//title/tt7131622/ratings',
 'https://www.imdb.com//title/tt0060827/ratings',
 'https://www.imdb.com//title/tt0119698/ratings',
 'https://www.imdb.com//title/tt0108052/ratings',
 'https://www.imdb.com//title/tt0021749/ratings',
 'https://www.imdb.com//title/tt0338013/ratings',
 'https://www.imdb.com//title/tt0978762/ratings',
 'https://www.imdb.com//title/tt0086250/ratings',
 'https://www.imdb.com//title/tt0405159/ratings',
 'https://www.imdb.com//title/tt0434409/ratings',
 'https://www.imdb.com//title/tt0086190/ratings',
 'https://www.imdb.com//title/tt0092005/ratings',
 'https://www.imdb.com//title/tt0071853/ratings',
 'https://www.imdb.com//title/tt0060196/ratings',
 'https://www.imdb.com//title/tt0112641/ratings',
 'https://www.imdb.com//title/tt0073486/ratings',
 'https://www.imdb.com//title/tt3170832/ratings',
 'https://www.imdb.com//title/tt4016934/ratings',
 'https://www.imdb.com//title/tt4633694/ratings',
 'https://www.imdb.com//title/tt0102926/ratings',
 'https://www.imdb.com//title/tt0107207/ratings',
 'https://www.imdb.com//title/tt0347149/ratings',
 'https://www.imdb.com//title/tt0871510/ratings',
 'https://www.imdb.com//title/tt0087544/ratings',
 'https://www.imdb.com//title/tt0468569/ratings',
 'https://www.imdb.com//title/tt0120689/ratings',
 'https://www.imdb.com//title/tt0078748/ratings',
 'https://www.imdb.com//title/tt0043014/ratings',
 'https://www.imdb.com//title/tt0075314/ratings',
 'https://www.imdb.com//title/tt0116282/ratings',
 'https://www.imdb.com//title/tt0064115/ratings',
 'https://www.imdb.com//title/tt0993846/ratings',
 'https://www.imdb.com//title/tt1392190/ratings',
 'https://www.imdb.com//title/tt0118694/ratings',
 'https://www.imdb.com//title/tt0066921/ratings',
 'https://www.imdb.com//title/tt0075148/ratings',
 'https://www.imdb.com//title/tt0058946/ratings',
 'https://www.imdb.com//title/tt0317248/ratings',
 'https://www.imdb.com//title/tt0208092/ratings',
 'https://www.imdb.com//title/tt0084787/ratings',
 'https://www.imdb.com//title/tt0032553/ratings',
 'https://www.imdb.com//title/tt0046438/ratings',
 'https://www.imdb.com//title/tt0046268/ratings',
 'https://www.imdb.com//title/tt0087843/ratings',
 'https://www.imdb.com//title/tt2338151/ratings',
 'https://www.imdb.com//title/tt0381681/ratings',
 'https://www.imdb.com//title/tt0395169/ratings',
 'https://www.imdb.com//title/tt1280558/ratings',
 'https://www.imdb.com//title/tt0061512/ratings',
 'https://www.imdb.com//title/tt0053291/ratings',
 'https://www.imdb.com//title/tt1291584/ratings',
 'https://www.imdb.com//title/tt0266697/ratings',
 'https://www.imdb.com//title/tt0910970/ratings',
 'https://www.imdb.com//title/tt0113247/ratings',
 'https://www.imdb.com//title/tt1028532/ratings',
 'https://www.imdb.com//title/tt1979376/ratings',
 'https://www.imdb.com//title/tt0060107/ratings',
 'https://www.imdb.com//title/tt0044741/ratings',
 'https://www.imdb.com//title/tt0119488/ratings',
 'https://www.imdb.com//title/tt6966692/ratings',
 'https://www.imdb.com//title/tt2267998/ratings',
 'https://www.imdb.com//title/tt0180093/ratings',
 'https://www.imdb.com//title/tt0046912/ratings',
 'https://www.imdb.com//title/tt2096673/ratings',
 'https://www.imdb.com//title/tt0079470/ratings',
 'https://www.imdb.com//title/tt0050083/ratings',
 'https://www.imdb.com//title/tt0082971/ratings',
 'https://www.imdb.com//title/tt0082096/ratings',
 'https://www.imdb.com//title/tt0086879/ratings',
 'https://www.imdb.com//title/tt0110413/ratings',
 'https://www.imdb.com//title/tt0055031/ratings',
 'https://www.imdb.com//title/tt0107290/ratings',
 'https://www.imdb.com//title/tt0268978/ratings',
 'https://www.imdb.com//title/tt0088247/ratings',
 'https://www.imdb.com//title/tt0019254/ratings',
 'https://www.imdb.com//title/tt0469494/ratings',
 'https://www.imdb.com//title/tt0051201/ratings',
 'https://www.imdb.com//title/tt0169858/ratings',
 'https://www.imdb.com//title/tt0111161/ratings',
 'https://www.imdb.com//title/tt0057115/ratings',
 'https://www.imdb.com//title/tt0097165/ratings',
 'https://www.imdb.com//title/tt1201607/ratings',
 'https://www.imdb.com//title/tt0053198/ratings',
 'https://www.imdb.com//title/tt0457430/ratings',
 'https://www.imdb.com//title/tt0093779/ratings',
 'https://www.imdb.com//title/tt0050212/ratings',
 'https://www.imdb.com//title/tt0097576/ratings',
 'https://www.imdb.com//title/tt0099685/ratings',
 'https://www.imdb.com//title/tt0353969/ratings',
 'https://www.imdb.com//title/tt0090605/ratings',
 'https://www.imdb.com//title/tt0169547/ratings',
 'https://www.imdb.com//title/tt0054215/ratings',
 'https://www.imdb.com//title/tt0038650/ratings',
 'https://www.imdb.com//title/tt0088763/ratings',
 'https://www.imdb.com//title/tt0094625/ratings',
 'https://www.imdb.com//title/tt2015381/ratings',
 'https://www.imdb.com//title/tt1187043/ratings',
 'https://www.imdb.com//title/tt0095327/ratings',
 'https://www.imdb.com//title/tt0482571/ratings',
 'https://www.imdb.com//title/tt0986264/ratings',
 'https://www.imdb.com//title/tt0093058/ratings',
 'https://www.imdb.com//title/tt0081398/ratings',
 'https://www.imdb.com//title/tt0057012/ratings',
 'https://www.imdb.com//title/tt0119217/ratings',
 'https://www.imdb.com//title/tt0062622/ratings',
 'https://www.imdb.com//title/tt0120815/ratings',
 'https://www.imdb.com//title/tt0087884/ratings',
 'https://www.imdb.com//title/tt0052618/ratings',
 'https://www.imdb.com//title/tt0062229/ratings',
 'https://www.imdb.com//title/tt0167260/ratings',
 'https://www.imdb.com//title/tt0211915/ratings',
 'https://www.imdb.com//title/tt0052357/ratings',
 'https://www.imdb.com//title/tt0095016/ratings',
 'https://www.imdb.com//title/tt0118849/ratings',
 'https://www.imdb.com//title/tt2106476/ratings',
 'https://www.imdb.com//title/tt0167404/ratings',
 'https://www.imdb.com//title/tt1675434/ratings',
 'https://www.imdb.com//title/tt0053604/ratings',
 'https://www.imdb.com//title/tt0120737/ratings',
 'https://www.imdb.com//title/tt0045152/ratings',
 'https://www.imdb.com//title/tt0032976/ratings',
 'https://www.imdb.com//title/tt0435761/ratings',
 'https://www.imdb.com//title/tt1853728/ratings',
 'https://www.imdb.com//title/tt0816692/ratings',
 'https://www.imdb.com//title/tt0091251/ratings',
 'https://www.imdb.com//title/tt0120731/ratings',
 'https://www.imdb.com//title/tt1979320/ratings',
 'https://www.imdb.com//title/tt0245712/ratings',
 'https://www.imdb.com//title/tt4430212/ratings',
 'https://www.imdb.com//title/tt0338564/ratings',
 'https://www.imdb.com//title/tt0266543/ratings',
 'https://www.imdb.com//title/tt0078788/ratings',
 'https://www.imdb.com//title/tt0120735/ratings',
 'https://www.imdb.com//title/tt0047396/ratings',
 'https://www.imdb.com//title/tt0405094/ratings',
 'https://www.imdb.com//title/tt0476735/ratings',
 'https://www.imdb.com//title/tt2119532/ratings',
 'https://www.imdb.com//title/tt1130884/ratings',
 'https://www.imdb.com//title/tt2278388/ratings',
 'https://www.imdb.com//title/tt0105236/ratings',
 'https://www.imdb.com//title/tt8108198/ratings',
 'https://www.imdb.com//title/tt0405508/ratings',
 'https://www.imdb.com//title/tt0367110/ratings',
 'https://www.imdb.com//title/tt0015864/ratings',
 'https://www.imdb.com//title/tt0114814/ratings',
 'https://www.imdb.com//title/tt0042192/ratings',
 'https://www.imdb.com//title/tt0114709/ratings',
 'https://www.imdb.com//title/tt1049413/ratings',
 'https://www.imdb.com//title/tt0172495/ratings',
 'https://www.imdb.com//title/tt0253474/ratings']

In [129]:
# url_r = links_r[0]

# r_r = requests.get(url_r)

# url_r
# soup_r = BeautifulSoup(r_r.text,'html.parser')
# soup_r


# table = soup_r.find('table', attrs={'class':'ratingTable selected'})
# table
# #table_body = table.find('tbody')
# #table_body




# #def rating_all_all(soup):
# #    for i in soup_r.find('table')
# #    return i
# #rating_all_all(soup_r)

# Ratings function (main function)

In [121]:
def ratings_extractor(url):
    r_r, call_id = connector.get(url, "ROFLMAO")
    try:
        title = soup_r.select("#main > section > div > div.subpage_title_block > div > div.parent > h3 > a")[0].text
        rating_a_a = rating_all_all(soup_r)
    except:
        title = None
        rating_a_a = None
        
    return {
        'title': title,
        'rating_a_a': rating_a_a
        }

ratings_extractor(url_r)

{'title': 'Rashomon - Dæmonernes port', 'rating_a_a': 8.2}

# Subfunctions

In [3]:
def find_budget(soup):
    for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
        if i.find().text == "Budget:":
            return float(i.text.strip().split("\n")[0].split("$")[1].replace(",", ""))
        
def find_gross(soup):
    for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
        if i.find().text == "Cumulative Worldwide Gross:":
            return float(i.text.strip().split("\n")[0].split("$")[1].replace(",", ""))
        
def find_grossUSA(soup):
    for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
        if i.find().text == "Gross USA:":
            return float(i.text.strip().split("\n")[0].split("$")[1].replace(",", ""))

def find_rating(soup):
    for i in soup.find(id="title-overview-widget").find_all("div", class_="ratingValue"):
        return i.text.strip().split("/")[0]
        
def find_runtime(soup):
    for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
        if i.find().text == "Runtime:":
            return float(i.text.strip().split("\n")[1].split("min")[0].strip())
def find_date(soup):
    for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
        if i.find().text == "Release Date:":
            return i.text.strip().split(":")[1].split("(")[0].strip()
        
def find_genre(soup):
    for i in soup.find(id="title-overview-widget").find_all("div", class_="subtext"):
        if str(i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(","))[-3]==(')'):
            return i.text.strip().split("|")[1].replace('\n','').replace(' ','').split(",")
        else:
            return i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(",")
        
def preparedatetime(dataframe):
    dataframe['datetime'] = pd.to_datetime(dataframe['date'], format = '%d %B %Y')
    dataframe['month'] = dataframe.datetime.dt.month
    dataframe['month'] = dataframe.datetime.dt.day
    dataframe['month'] = dataframe.datetime.dt.year

In [4]:

# def page_extractor(url):
#     r, call_id = connector.get(url, "LOL")
#     try:
#         soup = BeautifulSoup(r.text, "html.parser")
#         title, year = soup.select("#title-overview-widget > div.vital > div.title_block > div > div.titleBar > div.title_wrapper > h1")[0].text.split("\xa0")
#         budget = find_budget(soup)
#         cumulative_worldwide_gross=find_gross(soup)
#         gross_usa=find_grossUSA(soup)
#         rating = find_rating(soup)
#         runtime = find_runtime(soup)
#         date= find_date(soup)
#         genre = find_genre(soup)
#     except:
#         soup = None
#         title = None
#         budget = None
#         cumulative_worldwide_gross= None
#         gross_usa = None
#         rating=None
#         runtime = None
#         date = None
#         genre = None
#     return {
#         "title": title,
#         "year": year,
#         "budget": budget,
#         "url": url,
#         "cumulative_world_gross": cumulative_worldwide_gross,
#         "gross_usa": gross_usa,
#         "rating": rating,
#         "runtime": runtime,
#         "date": date,
#         "genre": genre
#     }

# #Husk at finde titel på engelsk

### Create a list and append information from every movie on the list. 
Remark: We have only chosen the first 15 so far, as to not make the coding too slow in progress. If you wish to see the whole list simply delete the [:15]

In [10]:
# res = []
# for idx, i in enumerate(links[:15]):
#     print(idx + 1, "of", len(links[:15]))
#     if 
#     else 
#     res.append(page_extractor(i))

1 of 15
Budget:$3,000,000
            (estimated)
2 of 15
Budget:$40,000,000
            (estimated)
3 of 15
Budget:$15,000,000
            (estimated)
4 of 15
Budget:$13,000,000
            (estimated)
5 of 15
Budget:$9,400,000
            (estimated)
6 of 15
Budget:$35,000,000
            (estimated)
7 of 15
Budget:TRL 1,200,000
            (estimated)
https://www.imdb.com//title/tt0116231/ didnt work
8 of 15
Budget:$950,000
            (estimated)
9 of 15
Budget:$20,000,000
            (estimated)
10 of 15
Budget:£6,000,000
            (estimated)
https://www.imdb.com//title/tt0208092/ didnt work
11 of 15
Budget:$250,000
            (estimated)
12 of 15
Budget:$11,000,000
            (estimated)
13 of 15
Budget:$1,500,000
            (estimated)
14 of 15
Budget:$94,000,000
            (estimated)
15 of 15
Budget:$800,000
            (estimated)

### Making our list into a dataframe. 

A dataframe is basically just when a list has both several columns and rows, if there's only one row it's an array.

In [11]:
# df = pd.DataFrame(res)


# df['datetime'] = pd.to_datetime(df['date'], format = '%d %B %Y')
# df

,budget,cumulative_world_gross,date,genre,gross_usa,rating,runtime,title,url,year,datetime
0,3000000.0,1.000000e+07,19 December 1961,"[Drama, War]",6000000.0,8.2,186.0,Dommen i Nürnberg,https://www.imdb.com//title/tt0055031/,(1961),1961-12-19
1,40000000.0,1.753024e+08,10 November 2016,"[Biography, Drama, History]",67209615.0,8.1,139.0,Hacksaw Ridge,https://www.imdb.com//title/tt2119532/,(2016),2016-11-10
2,15000000.0,4.618957e+07,21 August 1998,"[Comedy, Crime]",17498804.0,8.1,117.0,The Big Lebowski,https://www.imdb.com//title/tt0118715/,(1998),1998-08-21
3,13000000.0,NaN,29 August 1975,"[Crime, Drama]",57300000.0,9.0,202.0,Godfather del 2,https://www.imdb.com//title/tt0071562/,(1974),1975-08-29
4,9400000.0,NaN,31 July 2015,"[Crime, Drama, Mystery]",739478.0,8.3,163.0,Drishyam,https://www.imdb.com//title/tt4430212/,(2015),2015-07-31
5,35000000.0,1.200726e+08,4 July 2003,"[Biography, Drama, Music]",32572577.0,8.5,150.0,Pianisten,https://www.imdb.com//title/tt0253474/,(2002),2003-07-04
6,NaN,NaN,None,None,NaN,None,NaN,None,https://www.imdb.com//title/tt0116231/,(1996),NaT
7,950000.0,1.495262e+07,30 November 1946,"[Drama, Romance, War]",1024560.0,8.5,102.0,Casablanca,https://www.imdb.com//title/tt0034583/,(1942),1946-11-30
8,20000000.0,1.877332e+08,20 February 2014,"[Biography, Drama, History]",56671993.0,8.1,134.0,12 Years a Slave,https://www.imdb.com//title/tt2024544/,(2013),2014-02-20
9,NaN,NaN,None,None,NaN,None,NaN,None,https://www.imdb.com//title/tt0208092/,(2000),NaT
10,250000.0,NaN,2 March 1953,"[Crime, Drama, Mystery]",96568.0,8.2,88.0,Rashomon - Dæmonernes port,https://www.imdb.com//title/tt0042876/,(1950),1953-03-02
11,11000000.0,7.753980e+08,26 December 1977,"[Action, Adventure, Fantasy]",322740140.0,8.6,121.0,Stjernekrigen,https://www.imdb.com//title/tt0076759/,(1977),1977-12-26
12,1500000.0,NaN,1 May 1931,"[Comedy, Drama, Romance]",19181.0,8.5,87.0,Byens lys,https://www.imdb.com//title/tt0021749/,(1931),1931-05-01
13,94000000.0,1.119930e+09,17 December 2003,"[Adventure, Drama, Fantasy]",377845905.0,8.9,201.0,Ringenes herre: Kongen vender tilbage,https://www.imdb.com//title/tt0167260/,(2003),2003-12-17
14,800000.0,NaN,1 September 1967,"[Drama, War]",55908.0,8.1,121.0,Slaget om Algier,https://www.imdb.com//title/tt0058946/,(1966),1967-09-01

In [7]:
# df['datetime'] = pd.to_datetime(df['date'], format = '%d %B %Y')

# df['month'] = df.datetime.dt.month
# df['month'] = df.datetime.dt.day
# df['month'] = df.datetime.dt.year

In [8]:
# def preparedatetime(dataframe):
#     dataframe['datetime'] = pd.to_datetime(dataframe['date'], format = '%d %B %Y')
#     dataframe['month'] = dataframe.datetime.dt.month
#     dataframe['month'] = dataframe.datetime.dt.day
#     dataframe['month'] = dataframe.datetime.dt.year

# preparedatetime(df)
# df

In [9]:
# def find_budget(soup):
#     for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
#         if i.find().text == "Budget:":
#             print(i.text.strip())
#             return float(i.text.strip().split("\n")[0].split("$")[1].replace(",", ""))
        
# find_budget(s)

NameError: name 's' is not defined

In [ ]:
# def find_runtime(soup):
#     for i in soup.find(id="titleDetails").find_all("div", class_="txt-block"):
#         if i.find().text == "Runtime:":
#             return i.text.strip().split("\n")[1].split("min")[0].strip()
# find_runtime(soup_)

In [ ]:
# url_ = links[0]
# r = requests.get(url_)

# url_

In [ ]:
# soup_ = BeautifulSoup(r.text,'html.parser')

In [ ]:
# def find_genre(soup):
#     for i in soup.find(id="title-overview-widget").find_all("div", class_="subtext"):
#         return str(i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(","))
#         #return i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(",")

# find_genre(soup_)

In [ ]:
# def find_genre(soup):
#     for i in soup.find(id="title-overview-widget").find_all("div", class_="subtext"):
#         if str(i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(","))[-3]==(')'):
#             return i.text.strip().split("|")[1].replace('\n','').replace(' ','').split(",")
#         else:
#             return i.text.strip().split("|")[2].replace('\n','').replace(' ','').split(",")

# find_genre(soup_)

In [3]:
soup__ = BeautifulSoup(requests.get("https://www.imdb.com//title/tt0266543/ratings").text, "html.parser").select("#main > section > div > table:nth-child(14)")

soup__

[<table>
 <tr>
 <th class="firstTableColumn"></th>
 <th class="firstTable"><div class="tableHeadings">All Ages</div></th>
 <th class="firstTable"><div class="tableHeadings">&lt;18</div></th>
 <th class="firstTable"><div class="tableHeadings">18-29</div></th>
 <th class="firstTable"><div class="tableHeadings">30-44</div></th>
 <th class="firstTable"><div class="tableHeadings">45+</div></th>
 </tr>
 <tr height="70">
 <td class="noLeftBorder">
 <div class="allText"><div class="leftAligned">All</div></div>
 </td>
 <td align="center" class="ratingTable Selected">
 <div class="bigcell">8.1</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=imdb_users">
                     878,273
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.2</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=aged_under_18">
                     1,301
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.2</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=aged_18_29">
                     264,459
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.1</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=aged_30_44">
                     301,536
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable noRightBorder">
 <div class="bigcell">8.1</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=aged_45_plus">
                     62,365
                 </a>
 </div>
 </td>
 </tr>
 <tr height="70">
 <td class="noLeftBorder">
 <div class="allText"><div class="leftAligned">Males</div></div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.1</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=males">
                     502,577
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.3</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=males_aged_under_18">
                     915
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.2</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=males_aged_18_29">
                     186,807
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.0</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=males_aged_30_44">
                     231,965
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable noRightBorder">
 <div class="bigcell">8.0</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=males_aged_45_plus">
                     49,248
                 </a>
 </div>
 </td>
 </tr>
 <tr height="70">
 <td class="noLeftBorder">
 <div class="allText"><div class="leftAligned">Females</div></div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.3</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=females">
                     164,238
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.1</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=females_aged_under_18">
                     277
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.3</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=females_aged_18_29">
                     73,881
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable">
 <div class="bigcell">8.3</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=females_aged_30_44">
                     65,986
                 </a>
 </div>
 </td>
 <td align="center" class="ratingTable noRightBorder">
 <div class="bigcell">8.4</div>
 <div class="smallcell">
 <a href="/title/tt0266543/ratings?demo=females_aged_45_plus">
                     12,129
                 </a>
 </div>
 </td>
 </tr>
 </table>]

In [4]:
#loop leaves us with list of alle 15 ratings in order as 1st column row 1-5, 2nd column row 1-5, 3rd column row 1-5
rate = []
for i in soup__[0].find_all('div', class_='bigcell'):
    rate.append(i.text)
rate

#explains young and old
# list_young = np.array([float(i) for i in rate]) 
# young_position = [1, 2, 6, 7, 11, 12]
# rateyoung = list(list_young[young_position])

rateyoung = list(np.array([float(i) for i in rate])[[1, 2, 6, 7, 11, 12]])
rate_young = np.array(rateyoung).sum()/6
rate_young 
rateold = list(np.array([float(i) for i in rate])[[3,4,8,9,13,14]])
rate_old = np.array(rateold).sum()/6
rate_old

rate_mean = [float(i) for i in rate][0]
rate_male = [float(i) for i in rate][5]
rate_female = [float(i) for i in rate][10]
#these should either be added to the main table, or be imported as subtable and then do inner join on title
print('mean rating:', rate_mean, 
      '\nyoung rated:', rate_young, 
      '\nold rated:', rate_old, 
      '\nmale rating:', rate_male, 
      '\nfemale rating:', rate_female)

mean rating: 8.1
young rated: 8.216666666666667
old rated: 8.15
male rating: 8.1
female rating: 8.3

In [8]:
titles = []
for i in soup__[0].find("tr").find_all("th"):
    titles.append(i.text)
#titles
#rows
#res

#overflødigt fordi vi definer kolonnerne længere nede. Man kan ikke regne med dem med ulighedstegn og minus.

In [9]:
res = []
for row in soup__[0].find_all("tr")[1:]:
    rows = []
    for col in row.find_all("td"):
        rows.append(col.find("div").text)
    res.append(rows)
pd.DataFrame(res, columns=titles)


titless=['gender', 'all_ages', 'u18', '18_29', '30_44', 'o45']
df = pd.DataFrame(res, columns=titless)
df1 = df.set_index('gender')
df1

df1['all_ages'] = df1['all_ages'].astype(float)
df1['u18'] = df1['u18'].astype(float)
df1['18_29'] = df1['18_29'].astype(float)
df1['30_44'] = df1['30_44'].astype(float)
df1['o45'] = df1['o45'].astype(float)

df1['young'] = df1.loc[:,['u18','18_29']].sum(axis=1)/2 # - df1.loc['All','all_ages']
df1['old'] = df1.loc[:,['30_44','o45']].sum(axis=1)/2 # - df1.loc['All','all_ages']
df1

         all_ages  u18  18_29  30_44  o45  young   old
gender
All           8.2  8.1    8.2    8.2  8.3   8.15  8.25
Males         8.3  8.3    8.3    8.2  8.3   8.30  8.25
Females       8.1  7.4    8.0    8.1  8.2   7.70  8.15